### ISSUE TITLE
[TerrainMap.h] - operator porovnani

### ISSUE THREAD

**Issue by ksamlot** [klimamat/pia1-terrain#1]
`bool operator<  (Point const& v) const { return x + y*nx_max; };` operace vraci true pri kazdem nenulovem vysledku

`bool operator<  (Point const& v) const { return x + y*nx_max < v.x + v.y*nx_max; };` operace vrati porovnani hodnot

**Comment by klimamat** [comment]
Je to tak, diky za opravu chyby
